id: leak_detected
alias: Leak Detected
trigger:
  - platform: state
    entity_id: binary_sensor.leak_bathroom_water_leak
    to: "on"
  - platform: state
    entity_id: binary_sensor.leak_kitchen_water_leak
    to: "on"
action:
  - service: notify.mobile_app_luis_handy
    data:
      message: TTS
      data:
        ttl: 0
        priority: high
        media_stream: alarm_stream_max
        tts_text: "A leak has been detected in area {{ area_name(trigger.entity_id) }}"
  - service: notify.mobile_app_luis_handy
    data:
      title: "Leak Detected"
      message: "A leak has been detected in area {{ area_name(trigger.entity_id) }}"
      data:
        ttl: 0
        priority: high
