id: going_out
alias: Going Out
trigger:
  platform: state
  entity_id: person.luis_beu
  to: "not_home"
action:
  - service: climate.set_preset_mode
    entity_id: all
    data:
      preset_mode: "away"
  - if:
      - condition: template
        value_template: "{{ states.light | selectattr('state', 'eq', 'on') | list | length > 0 }}"
    then:
      - service: notify.notify
        data:
          title: "Lights left on"
          message: >-
            The following lights are still on:
            {% for light in states.light %}
            {%- if light.state == "on" %}
              - {{ light.name }}
            {%- endif %}
            {% endfor %}
          data:
            actions:
              - action: "turn_off_lights"
                title: "Turn off lights"
  - if:
      - condition: state
        entity_id: binary_sensor.all_windows
        state: "on"
    then:
      - service: notify.notify
        data_template:
          title: "Windows open"
          message: >-
            The following windows are open:
            {% for window in expand('binary_sensor.all_windows') %}
            {%- if window.state == 'on' %} 
              - {{ window.name }}
            {%- endif %}
            {% endfor %}
  - if:
    - condition: state
      entity_id: lock.home_door
      state: "unlocked"
    then:
      - service: notify.notify
        data:
          title: "Door unlocked"
          message: The door is unlocked
          data:
            actions:
              - action: "lock_door"
                title: "Lock door"
