id: morning_prepare
alias: Morning Prepare
trigger:
  platform: time
  at: "08:30:00"
condition: "{{ is_state('person.luis_beu', 'home') }}"
action:
  - service: climate.set_preset_mode
    entity_id: all
    data:
      preset_mode: "home"
    