id: toothbrush_button_pressed
alias: Toothbrush Button Pressed
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/Toothbrush Button/action"
  payload: "press"
action:
  - service: light.turn_on
    entity_id: light.bathroom_light
    data:
      effect: breathe
  - delay: 00:00:1
  - service: light.turn_on
    entity_id: light.bathroom_light
    data:
      effect: stop_effect
