id: zigbee2mqtt_join_disabled
alias: Zigbee2MQTT Join Disabled
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee2mqtt_permit_join
  - platform: state
    entity_id: switch.zigbee2mqtt_main_join
    to: "off"
action:
  - service: timer.cancel
    data:
      entity_id: timer.zigbee2mqtt_permit_join
  - service: switch.turn_off
    entity_id: switch.zigbee2mqtt_main_join