id: zigbee2mqtt_join_enabled
alias: Zigbee2MQTT Join Enabled
trigger:
  platform: state
  entity_id: switch.zigbee2mqtt_main_join
  to: "on"
action:
  service: timer.start
  entity_id: timer.zigbee2mqtt_permit_join
  data_template:
    duration: "{{ '00:0%i:00' % (states('input_number.zigbee2mqtt_join_minutes') | int ) }}"