id: "zigbee2mqtt_create_notification_on_successful_interview"
alias: Zigbee Device Joined Notification
trigger:
  platform: mqtt
  topic: 'zigbee2mqtt/bridge/event'
condition:
  condition: template
  value_template: '{{trigger.payload_json.type == "device_interview" and trigger.payload_json.data.status == "successful" and trigger.payload_json.data.supported}}'
action:
  - service: persistent_notification.create
    data_template:
      title: Device joined the Zigbee2MQTT network
      message: "Name: {{trigger.payload_json.data.friendly_name}},
                Vendor: {{trigger.payload_json.data.definition.vendor}},
                Model: {{trigger.payload_json.data.definition.model}},
                Description: {{trigger.payload_json.data.definition.description}}"