homeassistant:
  name: Home
  latitude: !env_var LATITUDE
  longitude: !env_var LONGITUDE
  unit_system: metric
  time_zone: Europe/Berlin
  currency: EUR
  elevation: 532

default_config:

mqtt: !include mqtt.yaml

sensor: !include_dir_list sensors/homeassistant/

recorder: !include recorder.yaml

lovelace: !include lovelace.yaml

climate: !include climate.yaml

# TODO: write comments
# TODO: get rid of sony tv
# TODO: do sleep as scene

automation: !include_dir_list automations/

script: !include_dir_named scripts/

input_number: !include_dir_named inputs/numbers/

input_text: !include_dir_named inputs/texts/

timer: !include_dir_named timers/
