homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  time_zone: Europe/Berlin

default_config:

mqtt: !include mqtt.yaml

recorder: !include recorder.yaml

lovelace: !include lovelace.yaml

climate: !include climate.yaml