- platform: generic_thermostat
  name: Living Room
  heater: switch.living_room_heater
  target_sensor: sensor.living_room_thermostat_temperature
  target_temp: 22
- platform: generic_thermostat
  name: Bedroom
  heater: switch.bedroom_heater
  target_sensor: sensor.bedroom_thermostat_temperature
  target_temp: 22