homeassistant: true
mqtt:
  user: mqtt
  base_topic: zigbee2mqtt
  server: mqtt://eclipse-mosquitto
serial:
  port: /dev/ttyACM0
devices:
  # Thermostats
  '0x44e2f8fffe239e10':
    friendly_name: Living Room Thermostat
  '0x44e2f8fffe33a949':
    friendly_name: Bedroom Thermostat
  '0x44e2f8fffe33aed7':
    friendly_name: Kitchen Thermostat
  '0x44e2f8fffe33b931':
    friendly_name: Bathroom Thermostat
  '0x44e2f8fffe27efaf':
    friendly_name: Toilet Thermostat

  # Heaters
  '0xc4988600000f774f':
    friendly_name: Living Room Heater
  '0xc4988600000f9b7b':
    friendly_name: Bedroom Heater

  # Lights
  '0x00178801067afd51':
    friendly_name: Living Room Dining Table Light
  '0x00178801093da33f':
    friendly_name: Living Room Coffee Table Light
  '0x001788010bb3f847':
    friendly_name: Bedroom Workbench Light
  '0x001788010c0b0a14':
    friendly_name: Bedroom Light
  '0x001788010bb578aa':
    friendly_name: Bathroom Light
  '0x001788010c01960e':
    friendly_name: Kitchen Light
  '0x001788010e2cd614':
    friendly_name: Bedroom Desk Backlight
  '0x001788010e311547':
    friendly_name: Kitchen Workbench Light

  # Switches
  '0x0000000001739bb6':
    friendly_name: Living Room Switch
  '0x001788010cc3328c':
    friendly_name: Bedroom Desk Switch
  '0x001788010cc3328e':
    friendly_name: Bedroom Bed Switch
  '0x001788010cc3328f':
    friendly_name: Bathroom Switch
  '0x001788010cc3328d':
    friendly_name: Kitchen Switch

  # Windows
  '0x00158d0008d9423c':
    friendly_name: Living Room Window
  '0x00158d000891f691':
    friendly_name: Bedroom Window

  # Buttons
  '0x00178801089632dc':
    friendly_name: Bedroom Workbench Button
  '0x00158d0009f50653':
    friendly_name: One Button To Rule Them All

  # Sockets
  '0xa4c1380991781f75':
    friendly_name: Bathroom Washing Machine Socket

  # Leak sensor
  '0x842712fffe825860':
    friendly_name: Leak Kitchen
  '0x842712fffe825861':
    friendly_name: Leak Bathroom
