homeassistant: true
frontend: true
mqtt:
  user: mqtt
  base_topic: zigbee2mqtt
  server: mqtt://eclipse-mosquitto
serial:
  port: /dev/ttyACM0
devices:
  '0x00124b00251394b8':
    friendly_name: Living Room Thermostat
  '0xc4988600000f774f':
    friendly_name: Living Room Heater
  '0x00124b002512fbaf':
    friendly_name: Bedroom Thermostat
  '0xc4988600000f9b7b':
    friendly_name: Bedroom Heater
  '0x001788010bb3f847':
    friendly_name: Workbench
  '0x0000000001739bb6':
    friendly_name: Living Room Switch
