id: bedroom_light_toggle
alias: Bedroom Light
trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/Bedroom Desk Switch/action"
    payload: "left_press"
  - platform: mqtt
    topic: "zigbee2mqtt/Bedroom Bed Switch/action"
    payload: "left_press"
action:
  service: light.toggle
  entity_id: light.bedroom_light