id: bedroom_light
alias: Bedroom Light
trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/Bedroom Desk Switch/action"
    payload: left_press
  - platform: mqtt
    topic: "zigbee2mqtt/Bedroom Bed Switch/action"
action:
  service: light.toggle
  target:
    entity_id: light.bedroom_lights_simple
