id: bedroom_workbench_light_toggle
alias: Workbench Light
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/Bedroom Workbench Button/action"
  payload: "press"
action:
  service: light.toggle
  entity_id: light.bedroom_workbench_light