id: bedroom_workbench_light_on
alias: Coffee Table Light On
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/Livingroom Switch/action"
  payload: "press_1"
action:
  service: light.turn_on
  entity_id: light.livingroom_coffee_table_light