id: bedroom_workbench_light_off
alias: Coffee Table Light Off
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/Living Room Switch/action"
  payload: "press_2"
action:
  service: light.turn_off
  entity_id: light.living_room_coffee_table_light