id: bedroom_workbench_light_off
alias: Coffee Table Light Off
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/Livingroom Switch/action"
  payload: "press_2"
action:
  service: light.turn_off
  entity_id: light.livingroom_coffee_table_light