id: living_room_lights
alias: Living Room Lights
trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/Living Room Switch/action"
    payload: "press_1_and_3"
  - platform: mqtt
    topic: "zigbee2mqtt/Living Room Switch/action"
    payload: "press_2_and_4"
action:
  - if:
    - condition: template
      value_template: "{{ trigger.payload == 'press_1_and_3' }}"
    then:
      - service: light.turn_on
        target:
          entity_id: light.living_room_lights
    else:
      - service: light.turn_off
        target:
          entity_id: light.living_room_lights