id: forest_light_cycle
alias: "Forest light cycle"
trigger:
  platform: state
  entity_id: input_select.dnd_light_mood
  to: "Forest"
action:
  - variables:
      rgb_values:
        - [31, 128, 45] # Mossy green
        - [60, 145, 32] # Leafy green
        - [143, 188, 143] # darkseagreen
        - [139, 170, 70] # Fern green
        - [189, 208, 99] # Spring green
        - [226, 234, 169] # Pale green
        - [107, 142, 35] # olivedrab
        - [173, 255, 47] # greenyellow
  - repeat:
      while:
        - condition: state
          entity_id: input_select.dnd_light_mood
          state: "Forest"
      sequence:
        - variables:
            color_index: "{{ range(0, rgb_values|length)|random }}"
        - service: light.turn_on
          entity_id:
            - light.living_room_dining_table_light
            - light.living_room_coffee_table_light
          data:
            brightness: 255
            transition: 15
            rgb_color: "{{ rgb_values[color_index] }}"
        - delay: 30
